name: 'Badge To Path'
author: 'Jan-Petter Krüger'
description: 'A simple action that creates and writes a badge to a specified path'
inputs:
  label:
    description: The left label of the badge, usually static.
    default: ':label'
    required: false
  message:
    description: The right status as the badge, usually based on results.
    default: ':status'
    required: false
  path:
    description: Output image path.
    default: badge.svg
    required: true
  labelColor:
    description: The color for the label part of the badge
    default: '#007ec6'
    required: false
  messageColor:
    description: The color for the message part of the badge
    default: '#9f9f9f'
    required: false
  github-token:
    description: GitHub token
    required: true
runs:
  using: "composite"
  steps:
    - id: install-jbang
      run: curl -Ls https://sh.jbang.dev | bash -s - app setup
      shell: bash
    - id: action
      run: ~/.jbang/bin/jbang --repos 'github=https://maven.pkg.github.com/janpk/badge-to-path.git/' --repos 'mavencentral' dev.hagastua.action.badgetopath:badge-to-path:999-SNAPSHOT
      shell: bash
      env:
        JSON_INPUTS: ${{ toJSON(inputs) }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
