name: 'Badge To Path'
author: 'Jan-Petter Krüger'
description: 'A simple action that creates and writes a badge to a specified path'
branding:
  icon: bold
  color: yellow
inputs:
  style:
    description: The style to apply to the badge
    default: 'flat'
    required: false
  label:
    description: The left label of the badge, usually static.
    default: ':label'
    required: true
  message:
    description: The right status of the badge, usually based on results.
    default: ':message'
    required: true
  path:
    description: Output image path.
    required: false
  labelColor:
    description: The color for the label part of the badge
    default: '#007ec6'
    required: false
  messageColor:
    description: The color for the message part of the badge
    default: '#9f9f9f'
    required: false
  logo:
    description: A logo to add to the generated badge
    required: false
  logoWidth:
    description: The width of the logo if you would like something other than the default
    default: '0'
    required: false
  link:
    description: A link to add to the generated badge
    required: false
  github-token:
    description: GitHub token
    required: true
outputs:
  badge-src:
    description: The badge svg xml source
    value: ${{steps.action.outputs.badge-src}}
runs:
  using: "composite"
  steps:
    - id: install-jbang
      run: curl -Ls https://sh.jbang.dev | bash -s - app setup
      shell: bash
    - id: action
      run: ~/.jbang/bin/jbang --repos 'github=https://maven.pkg.github.com/janpk/badge-to-path.git/' --repos 'mavencentral' dev.hagastua.action.badgetopath:badge-to-path:1.0.3
      shell: bash
      env:
        JSON_INPUTS: ${{ toJSON(inputs) }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
